# Generated by Django 5.0.3 on 2024-06-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=10, null=True)),
                ('First_name', models.CharField(max_length=50, null=True)),
                ('Last_name', models.CharField(max_length=50, null=True)),
                ('Vendor_email', models.EmailField(max_length=254, null=True)),
                ('Mobile', models.CharField(max_length=25, null=True)),
                ('Company_Name', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Website', models.CharField(default='', max_length=100, null=True)),
                ('GST_Treatment', models.CharField(max_length=50, null=True)),
                ('GST_Number', models.CharField(max_length=50, null=True)),
                ('Pan_Number', models.CharField(max_length=50, null=True)),
                ('Opening_balance_type', models.CharField(max_length=50, null=True)),
                ('Opening_balance', models.FloatField(default=0.0, null=True)),
                ('Current_balance', models.FloatField(default=0.0, null=True)),
                ('Credit_limit', models.FloatField(default=0.0, null=True)),
                ('Place_of_supply', models.CharField(max_length=200, null=True)),
                ('Billing_street', models.CharField(max_length=200, null=True)),
                ('Billing_city', models.CharField(max_length=200, null=True)),
                ('Billing_state', models.CharField(max_length=200, null=True)),
                ('Billing_country', models.CharField(max_length=200, null=True)),
                ('Billing_pincode', models.CharField(max_length=10, null=True)),
                ('Shipping_street', models.CharField(max_length=200, null=True)),
                ('Shipping_city', models.CharField(max_length=200, null=True)),
                ('Shipping_state', models.CharField(max_length=200, null=True)),
                ('Shipping_country', models.CharField(max_length=200, null=True)),
                ('Shipping_pincode', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Login_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Vendor_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Action', models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=30, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('Login_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('Vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_vendor')),
            ],
        ),
    ]
